; here we have some of the definitions used as arguments



%define AF_INET        2    ;   IPv4 address family, for IPV6 would be 10
 
%define SOCK_STREAM    1    ;  SOCK_STREAM --> Provides sequenced, reliable, two-way, connection-based byte streams.

%define SOCK_PROTOCOL  0    ; default protocol for SOCK_STREAM


%define BACKLOG        2    ; maximum number of pending connections


%define CR 0xD ; \r
%define LF 0xA ; \n for the http response
